sonar.projectKey=jazambrano21_LogiFlow-Proyecto-Integrador
sonar.organization=jazambrano21
sonar.host.url=https://sonarcloud.io

# ── Fuentes Java (Fase 1 + Fase 2) ──────────────────────────────────────────
sonar.sources=\
  Backend/ms-flota/src/main/java,\
  Backend/ms-taller/src/main/java,\
  Backend/ms-auth/src/main/java,\
  Backend/ms-clientes/src/main/java,\
  Backend/ms-pedidos/src/main/java,\
  Backend/ms-ruteo/src/main/java,\
  Backend/ms-seguimiento/src,\
  Backend/graphql-gateway/src

# ── Tests Java ───────────────────────────────────────────────────────────────
sonar.tests=\
  Backend/ms-flota/src/test/java,\
  Backend/ms-taller/src/test/java,\
  Backend/ms-auth/src/test/java,\
  Backend/ms-clientes/src/test/java,\
  Backend/ms-pedidos/src/test/java,\
  Backend/ms-ruteo/src/test/java

# ── Binarios compilados ───────────────────────────────────────────────────────
sonar.java.binaries=\
  Backend/ms-flota/target/classes,\
  Backend/ms-taller/target/classes,\
  Backend/ms-auth/target/classes,\
  Backend/ms-clientes/target/classes,\
  Backend/ms-pedidos/target/classes,\
  Backend/ms-ruteo/target/classes

# ── Reportes JUnit ────────────────────────────────────────────────────────────
sonar.junit.reportPaths=\
  Backend/ms-flota/target/surefire-reports,\
  Backend/ms-taller/target/surefire-reports,\
  Backend/ms-auth/target/surefire-reports,\
  Backend/ms-clientes/target/surefire-reports,\
  Backend/ms-pedidos/target/surefire-reports,\
  Backend/ms-ruteo/target/surefire-reports

# ── Cobertura JaCoCo ─────────────────────────────────────────────────────────
sonar.coverage.jacoco.xmlReportPaths=\
  Backend/ms-flota/target/site/jacoco/jacoco.xml,\
  Backend/ms-taller/target/site/jacoco/jacoco.xml,\
  Backend/ms-auth/target/site/jacoco/jacoco.xml,\
  Backend/ms-clientes/target/site/jacoco/jacoco.xml,\
  Backend/ms-pedidos/target/site/jacoco/jacoco.xml,\
  Backend/ms-ruteo/target/site/jacoco/jacoco.xml

# ── Exclusiones ──────────────────────────────────────────────────────────────
sonar.exclusions=\
  **/node_modules/**,\
  **/.mvn/**,\
  **/target/**,\
  **/*.min.js
