sonar.projectKey=jazambrano21_LogiFlow-Proyecto-Integrador
sonar.organization=jazambrano21
sonar.host.url=https://sonarcloud.io
sonar.sources=Backend/ms-flota/src/main/java,Backend/ms-taller/src/main/java
sonar.tests=Backend/ms-flota/src/test/java,Backend/ms-taller/src/test/java
sonar.java.binaries=Backend/ms-flota/target/classes,Backend/ms-taller/target/classes
sonar.junit.reportPaths=Backend/ms-flota/target/surefire-reports,Backend/ms-taller/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=Backend/ms-flota/target/site/jacoco/jacoco.xml,Backend/ms-taller/target/site/jacoco/jacoco.xml
