# Cargar definiciones al arrancar (exchanges, queues, bindings)
load_definitions = /etc/rabbitmq/definitions.json

# Habilitar el plugin de management
management.load_definitions = /etc/rabbitmq/definitions.json
