server:
  port: 8081

spring:
  application:
    name: ms-autenticacion
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_auth}
    username: ${DB_USER:logiflow}
    password: ${DB_PASS:logiflow123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET:logiflow-secret-key-2026}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
