apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-clientes-config
  namespace: logiflow
data:
  PORT: "8082"
  DB_URL: "jdbc:mysql://mysql-clientes:3306/ms_clientes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  MS_AUTH_URL: "http://ms-auth:8081"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
