apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-auth-config
  namespace: logiflow
data:
  PORT: "8081"
  DB_URL: "jdbc:mysql://mysql-auth:3306/ms_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  JWT_EXPIRATION: "86400000"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
