services:
  mysql-facturacion:
    image: mysql:8.0
    container_name: mysql_facturacion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logiflow_facturacion
    ports:
      - "3310:3306"
    volumes:
      - mysql_facturacion_data:/var/lib/mysql

volumes:
  mysql_facturacion_data:
