spring.application.name=ms-clientes
server.port=${PORT:8082}

# Datasource
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3311/ms_clientes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT (mismo secreto que ms-auth)
jwt.secret=${JWT_SECRET:logiflow-secret-key-fase2-must-be-at-least-32-chars}

# ms-auth
ms-auth.base-url=${MS_AUTH_URL:http://localhost:8081}

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
