services:
  mysql-taller:
    image: mysql:8.0
    container_name: mysql_taller
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logiflow_taller
    ports:
      - "3309:3306"
    volumes:
      - mysql_taller_data:/var/lib/mysql
    networks:
      - taller-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-taller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-taller
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-taller:3306/logiflow_taller?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-taller:
        condition: service_healthy
    networks:
      - taller-network

volumes:
  mysql_taller_data:

networks:
  taller-network:
    driver: bridge
